### ISSUE TITLE
[FEATURE]: 대여 Button 공통 컴포넌트

### ISSUE THREAD

**Issue by cmj7271** [GDSC-Hongik/rental-system-mango-web#18]
## 기능에 대한 간단한 설명
기능에 대한 간단한 설명을 해주세요

대여/대기 여부로 버튼의 UI 가 달라짐

## TODO
- [ ] : 공통 대여 버튼 컴포넌트
- [ ] : 필요한 props 정리
- [ ] : api 연결(예시 api로 요청보내기)
